name: Add Issue to GitHub Project (Beta)

on:
  workflow_call:
    inputs:
      organization:
        description: "The name of the organization which the Project belongs to"
        default: "instill-ai"
        required: false
        type: string
      project_number:
        description: "The Project number"
        required: true
        type: number
    secrets:
      botGitHubToken:
        description: "A personal access token token (classic) with project and repo scopes"
        required: true
  issues:
    types:
      - opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        env:
          ORGANIZATION: ${{ inputs.organization }}
          PROJECT_NUMBER: ${{ inputs.project_number }}
        with:
          project-url: https://github.com/orgs/$ORGANIZATION/projects/$PROJECT_NUMBER
          github-token: ${{ secrets.botGitHubToken }}
